### ISSUE TITLE
Uninstall, display

### ISSUE THREAD

**Issue by cwsstkates** [scholarslab/NeatlineTime#89] opened 2018-04-25 01:46 UTC
I have been having trouble getting the Neatline Time working, and tried an uninstall. Now I cannot re-install. Output is as follows:

exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli statement execute error : Invalid default value for 'center_date'' in /var/www/html/omeka_Spring2017/application/libraries/Zend/Db/Statement/Mysqli.php:214
Stack trace:
#0 /var/www/html/omeka_Spring2017/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /var/www/html/omeka_Spring2017/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 [internal function]: Zend_Db_Adapter_Abstract->query('CREATE TABLE IF...')
#3 /var/www/html/omeka_Spring2017/application/libraries/Omeka/Db.php(79): call_user_func_array(Array, Array)
#4 /var/www/html/omeka_Spring2017/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->__call('query', Array)
#5 /var/www/html/omeka_Spring2017/plugins/NeatlineTime/NeatlineTimePlugin.php(64): Omeka_Db->query('CREATE TABLE IF...')
#6 [internal function]: NeatlineTimePlugin->hookInstall(Array)
#7 /var/www/html/omeka_Spring2017/application/libraries/Omeka/Plugin/Broker.php(145): call_user_func(Array, Array)
#8 /var/www/html/omeka_Spring2017/application/libraries/Omeka/Plugin/Installer.php(130): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin))
#9 /var/www/html/omeka_Spring2017/application/controllers/PluginsController.php(97): Omeka_Plugin_Installer->install(Object(Plugin))
#10 /var/www/html/omeka_Spring2017/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction()
#11 /var/www/html/omeka_Spring2017/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction')
#12 /var/www/html/omeka_Spring2017/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /var/www/html/omeka_Spring2017/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#14 /var/www/html/omeka_Spring2017/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#15 /var/www/html/omeka_Spring2017/application/libraries/Omeka/Application.php(77): Zend_Application->run()
#16 /var/www/html/omeka_Spring2017/admin/index.php(28): Omeka_Application->run()
#17 {main}

**Comment by Daniel-KM** [comment] 2018-05-02 09:16
The issue is fixed in pull requests or in my [fork](https://github.com/Daniel-KM/Omeka-plugin-NeatlineTime), not here yet.

**Comment by jeremyboggs** [comment] 2019-10-01 18:53
This issue should be addressed in the 2.1.1 tag.

**Closed by jeremyboggs** 2019-10-01 18:53 UTC
