### ISSUE TITLE
Can't load items

### ISSUE THREAD

**Issue by eugeniakim24** [scholarslab/NeatlineTime#74] opened 2016-04-14 04:11 UTC
Hello,

I've set the following parameters for the plug-in and the code reflects that it is there:
![image](https://cloud.githubusercontent.com/assets/18455460/14516881/27a8bdee-023a-11e6-8157-d313f2c2c03d.png)

However, not only does the display NOT center around 1961, it won't find any items from a specified collection or with the year '1961' in it:
![image](https://cloud.githubusercontent.com/assets/18455460/14516859/e63eadbe-0239-11e6-85fd-567056271e25.png)

Is there another setting to be configured? I've been looking through the Omeka forums but haven't a solution that works yet.

Thank you,
Eugenia

**Comment by csbailey5t** [comment] 2016-04-14 17:08
Hi Eugenia, are you developing your site locally or in production? If the latter, can you send provide a link? If I can take a look directly at the site, I should have a better chance of figuring out what's gone wrong. 

Thanks,
Scott

**Comment by eugeniakim24** [comment] 2016-04-15 00:51
Dear Scott,

The link is http://144.214.124.6:8000/omeka/neatline-time/timelines/show/1

We are trying to figure out how to use certain features before entering all
of our metadata into Omeka.

Thank you,
Eugenia

**Comment by erochest** [comment] 2016-04-15 13:12
Hi @eugeniakim24 ,

The problem is that you don't have any data being loaded into the timeline. Evidently it only sets the center date and moves the timeline there when there is data to display.

This may be a bit unexpected. We'll think about whether and how to address it.

HTH,

**Comment by csbailey5t** [comment] 2016-04-15 14:22
Hi @eugeniakim24, what item query are you using to specify the data? If you were using a query around a date, I would make sure to check that the date format on your items fits that needed by NeatlineTime. Here's some info on that: https://github.com/scholarslab/NeatlineTime#dates-for-items

**Comment by eugeniakim24** [comment] 2016-04-16 02:25
Dear Scott,
  The query is currently set to search by Collection.  The dates in the
DC:Date field are set to YYYY-MM-DD.

Thank you,
Eugenia

Disclaimer: the link provided above is just a test server and does not
represent a finished product in any way, shape, or form

**Comment by csbailey5t** [comment] 2016-04-19 14:47
Hi @eugeniakim24, would you be willing to create a user for me on your Omeka site? Without being able to directly looking at it, I'm not sure if I'll be able to figure out why your item query is not returning data. If that's alright, you can send me an email with credentials at csb5t[at]virginia.edu.

**Comment by jeremyboggs** [comment] 2019-10-01 13:47
@eugeniakim24 I'm going to close this issue, given its age and my sense that you may have received assistance already, through other communication. If this is still an issue and you need help, we can reopen it.

**Closed by jeremyboggs** 2019-10-01 13:47 UTC

**Comment by eugeniakim24** [comment] 2019-10-01 13:49
Hello,
 Thank you for the heads up. I actually gave up on the issue as I never
found a resolution.

Thank you.
